x-logging:
  &default-logging
  driver: "journald"
  options: 
    tag: "docker-metrics-stack"
    labels: "level"

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    restart: unless-stopped
    # https://github.com/prometheus/prometheus/issues/5976
    user: root
    ports:
      - 0.0.0.0:9090:9090
    volumes:
      - prometheus_data:/prometheus/data
      - ${PWD}/prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=1y"  # Set retention time to 1 year
      - "--storage.tsdb.retention.size=10GB" # Set retention size to 10 GB
    logging: *default-logging
    networks:
      - metrics

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      # Use this to set the default home dashboard
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/sample-metrics.json
    entrypoint:
      - /run.sh
    image: grafana/grafana-oss:10.4.2
    restart: unless-stopped
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ${PWD}/grafana_dashboards:/var/lib/grafana/dashboards
      - ${PWD}/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PWD}/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    logging: *default-logging
    networks:
      - metrics

  pushgateway:
    image: prom/pushgateway:v1.8.0
    ports:
      - 0.0.0.0:9091:9091
    restart: unless-stopped
    logging: *default-logging
    networks:
      - metrics

  loki:
    image: grafana/loki:2.9.8
    restart: unless-stopped
    ports:
      - 0.0.0.0:3100:3100
    volumes:
      - loki_data:/loki
      - ${PWD}/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
    networks:
      - metrics

  promtail:
    image: grafana/promtail:2.9.1
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ${PWD}/promtail-config.yml:/etc/promtail/config.yml
      - promtail_data:/promtail_data
    command: 
      - -config.file=/etc/promtail/config.yml
      # - -config.expand-env=true
    logging: *default-logging
    networks:
      - metrics

networks:
  metrics:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  promtail_data:
  loki_data:
  