{
 "title": "Sample Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "UK Time", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_ready > bool 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "REST API Servers ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"rest-api-servers\"} > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs - varlogs - host",
   "type": "logs",
   "gridPos": { "h": 22, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{host=\"yourhost\",job=\"varlogs\"}"
    }
   ]
  }
 ]
}